[package]
name = "example"
version = "0.1.0"
authors = ["Folkert <folkert@folkertdev.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket-crud-macros = { path = "../rocket_crud_macros/" }
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
diesel = { version = "1.4.6", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"

[dependencies.rocket_sync_db_pools]
git = "https://github.com/SergioBenitez/Rocket"
version = "0.1.0-dev"
features = ["diesel_postgres_pool"]
