###

GET http://localhost:8000/users?sort=username&sort=created_at&filter[username]in=arjen@tweedegolf.com HTTP/1.1
Accept: application/json

###

GET http://localhost:8000/users?sort=username&sort=created_at&filter[username]=arjen@tweedegolf.com HTTP/1.1
Accept: application/json

###

GET http://localhost:8000/users?sort=username&sort=created_at&offset=1&limit=1 HTTP/1.1
Accept: application/json

###

GET http://localhost:8000/users/1 HTTP/1.1
Accept: application/json

###

POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "username": "ruben@tweedegolf.com",
  "role": "ADMIN"
}

###

POST http://localhost:8000/users HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username=ruben@tweedegolf.com&role=ADMIN

###

POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "username": "arjen@tweedegolf.com",
  "role": "ADMIN"
}

###

POST http://localhost:8000/posts HTTP/1.1
Content-Type: application/json

{
  "title": "Second post",
  "subtitle": null,
  "content": "This is the second post!",
  "publish_date": "2021-01-01",
  "publish_time": "00:00:00",
  "user_id": 1
}

###

PATCH http://localhost:8000/posts/3 HTTP/1.1
Content-Type: application/json

{
  "title": "First post!"
}

###

PATCH http://localhost:8000/posts/3 HTTP/1.1
Content-Type: application/json

{
  "subtitle": "First post!!!!!!"
}

###

PATCH http://localhost:8000/posts/3 HTTP/1.1
Content-Type: application/json

{
  "subtitle": null
}

###

GET http://localhost:8000/posts HTTP/1.1
Content-Type: application/json
Accept: application/json
X-UNSAFE-USER-ID: 1

###

DELETE http://localhost:8000/users/1 HTTP/1.1
